cafewelchez/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from menu.views import indice

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('login/', auth_views.LoginView.as_view(), name='iniciar'),
    path('logout/', auth_views.LogoutView.as_view(), name='salir'),
    path('', indice, name='home'),
]

menu/urls.py
from django.urls import include, path
from rest_framework import routers

from . import api, views

# from material.frontend import urls as frontend_urls

router = routers.DefaultRouter()
router.register(r'restaurante', api.RestauranteViewSet)
router.register(r'categoria', api.CategoriaViewSet)
router.register(r'item', api.ItemViewSet)

urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Restaurante
    path('restaurante/', views.RestauranteListView.as_view(), name='menu_restaurante_list'),
    path('restaurante/crear/', views.RestauranteCreateView.as_view(), name='menu_restaurante_create'),
    path('restaurante/detalle/<slug:slug>/', views.RestauranteDetailView.as_view(), name='menu_restaurante_detail'),
    path('restaurante/editar/<slug:slug>/', views.RestauranteUpdateView.as_view(), name='menu_restaurante_update'),
)

urlpatterns += (
    # urls for Categoria
    path('categoria/', views.CategoriaListView.as_view(), name='menu_categoria_list'),
    path('categoria/crear/<int:restaurante_id>/', views.CategoriaCreateView.as_view(), name='menu_categoria_create'),
    path('categoria/detalle/<slug:slug>/', views.CategoriaDetailView.as_view(), name='menu_categoria_detail'),
    path('categoria/editar/<slug:slug>/', views.CategoriaUpdateView.as_view(), name='menu_categoria_update'),
)

urlpatterns += (
    # urls for Item
    path('item/', views.ItemListView.as_view(), name='menu_item_list'),
    path('item/crear/<int:categoria_id>/', views.ItemCreateView.as_view(), name='menu_item_create'),
    path('item/detalle/<slug:slug>/', views.ItemDetailView.as_view(), name='menu_item_detail'),
    path('item/editar/<slug:slug>/', views.ItemUpdateView.as_view(), name='menu_item_update'),
)

menu/models.py
# from django.conf import settings
# from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
# from django.contrib.auth import get_user_model
# from django.contrib.auth import models as auth_models
from django.db import models
# from django.db.models.functions import Coalesce
# from django_extensions.db.fields import AutoSlugField
from django.db.models import *
from django.urls import reverse
from django_extensions.db import fields as extension_fields


class Restaurante(models.Model):
    # Fields
    orden = models.IntegerField(null=True, blank=True)
    nombre = models.CharField(max_length=100)
    activo = models.BooleanField(default=True)
    lugar = models.CharField(max_length=100)
    texto_menu = models.TextField(max_length=255)
    platos = models.IntegerField(null=True, blank=True)
    slug = extension_fields.AutoSlugField(populate_from='nombre', blank=True, overwrite=True)
    creado = models.DateTimeField(auto_now_add=True, editable=False)
    actualizado = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        ordering = ('orden',)
        verbose_name_plural = 'Restaurantes'

    def __str__(self):
        return self.nombre

    def __unicode__(self):
        return u'%s' % self.nombre

    @property
    def count_platos(self):
        if self.categorias.exists():
            count_agregado = self.categorias.aggregate(items=Sum('platos'))
            return count_agregado['items']
        else:
            return 0

    def save(self, *args, **kwargs):
        self.platos = self.count_platos
        super(Restaurante, self).save()

    def get_absolute_url(self):
        return reverse('menu_restaurante_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('menu_restaurante_update', args=(self.slug,))


class Categoria(models.Model):

    # Fields
    orden = models.IntegerField(null=True, blank=True)
    nombre = models.CharField(max_length=100)
    activa = models.BooleanField(default=True)
    mask_height = models.IntegerField(null=True, blank=True)
    header_price_1 = models.TextField(max_length=100, null=True, blank=True)
    header_price_2 = models.TextField(max_length=100, null=True, blank=True)
    platos = models.IntegerField(null=True, blank=True)
    slug = extension_fields.AutoSlugField(populate_from='nombre', blank=True, overwrite=True)
    creada = models.DateTimeField(auto_now_add=True, editable=False)
    actualizada = models.DateTimeField(auto_now=True, editable=False)

    # Relationship Fields
    restaurante = models.ForeignKey('menu.Restaurante', on_delete=CASCADE, related_name='categorias')

    class Meta:
        ordering = ('orden',)
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'

    def __str__(self):
        return self.restaurante.nombre + ' - ' + self.nombre

    def __unicode__(self):
        return u'%s' % self.restaurante.nombre + ' - ' + self.nombre

    @property
    def count_platos(self):
        if self.items.exists():
            count_items = self.items.count()
            return count_items
        else:
            return 0

    def save(self, *args, **kwargs):
        elrestaurante = Restaurante.objects.get(id=self.restaurante.pk)
        self.platos = self.count_platos
        super(Categoria, self).save()
        elrestaurante.save()

    def get_absolute_url(self):
        return reverse('menu_categoria_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('menu_categoria_update', args=(self.slug,))


class Item(models.Model):

    # Fields
    orden = models.IntegerField(null=True, blank=True)
    nombre = models.CharField(max_length=100)
    activo = models.BooleanField(default=True)
    descripcion = models.CharField(max_length=100, null=True, blank=True, default=" ")
    nivel = models.IntegerField(null=True, blank=True, default=1)
    precio = models.IntegerField(null=True, blank=True, default=None)
    precio_2 = models.IntegerField(null=True, blank=True, default=None)
    slug = extension_fields.AutoSlugField(populate_from='nombre', blank=True, overwrite=True)
    creado = models.DateTimeField(auto_now_add=True, editable=False, null=True, blank=True)
    actualizado = models.DateTimeField(auto_now=True, editable=False, null=True, blank=True)

    # Relationship Fields
    categoria = models.ForeignKey('menu.Categoria', on_delete=CASCADE, related_name='items')

    class Meta:
        ordering = ('orden',)
        verbose_name = 'Ítem'
        verbose_name_plural = 'Ítems'

    def __str__(self):
        return self.nombre

    def __unicode__(self):
        return u'%s' % self.nombre

    @property
    def restaurante(self):
        return self.categoria.restaurante.nombre

    def save(self, *args, **kwargs):
        lacategoria = Categoria.objects.get(id=self.categoria.pk)
        if self.precio == 0:
            self.precio = None
        if self.precio_2 == 0:
            self.precio_2 = None
        super(Item, self).save()
        lacategoria.save()

    def get_absolute_url(self):
        return reverse('menu_item_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('menu_item_update', args=(self.slug,))

menu/forms.py
from django import forms
from django.forms import Textarea
from material import Layout, Row

from .models import Categoria, Item, Restaurante


class RestauranteForm(forms.ModelForm):
    class Meta:
        model = Restaurante
        fields = ['orden', 'nombre', 'lugar', 'activo', 'texto_menu']
        widgets = {
            'texto_menu': Textarea(attrs={'cols': 40, 'rows': 2})
        }

    layout = Layout(Row('orden', 'activo'),
                    'nombre', 'lugar',
                    'texto_menu')


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['orden', 'nombre', 'activa', 'mask_height', 'header_price_1', 'header_price_2']
        exclude = ['restaurante']

    layout = Layout(Row('orden', 'activa'),
                    'nombre',
                    Row('mask_height', 'header_price_1', 'header_price_2'))


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['orden', 'nombre', 'nivel', 'descripcion', 'precio', 'precio_2', 'activo']
        exclude = ['categoria']

    layout = Layout(Row('orden', 'activo'),
                    'nombre', 'descripcion',
                    Row('nivel', 'precio', 'precio_2'))

menu/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import Restaurante, Categoria, Item
from .forms import RestauranteForm, CategoriaForm, ItemForm


def indice(request):
    """
    :param request:
    :return: Listado de Restaurantes
    """

    restaurantes = Restaurante.objects.all()
    return render(request, "menu/index.html", {'restaurantes': restaurantes})


class RestauranteListView(ListView):
    model = Restaurante


class RestauranteCreateView(CreateView):
    model = Restaurante
    form_class = RestauranteForm


class RestauranteDetailView(DetailView):
    model = Restaurante


class RestauranteUpdateView(UpdateView):
    model = Restaurante
    form_class = RestauranteForm


class CategoriaListView(ListView):
    model = Categoria


class CategoriaCreateView(CreateView):
    model = Categoria
    form_class = CategoriaForm

    def form_valid(self, form):
        categoria = form.save(commit=False)
        restaurante_id = form.data['restaurante']
        restaurante = get_object_or_404(Restaurante, id=restaurante_id)
        categoria.restaurante = restaurante
        return super(CategoriaCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CategoriaCreateView, self).get_context_data(**kwargs)
        context['r_id'] = self.kwargs['restaurante_id']
        return context

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = self.object.restaurante.slug
        return reverse('menu_restaurante_detail', kwargs={'slug': slug})


class CategoriaDetailView(DetailView):
    model = Categoria


class CategoriaUpdateView(UpdateView):
    model = Categoria
    form_class = CategoriaForm


class ItemListView(ListView):
    model = Item


class ItemCreateView(CreateView):
    model = Item
    form_class = ItemForm

    def form_valid(self, form):
        item = form.save(commit=False)
        categoria_id = form.data['categoria']
        categoria = get_object_or_404(Categoria, id=categoria_id)
        item.categoria = categoria
        return super(ItemCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ItemCreateView, self).get_context_data(**kwargs)
        context['c_id'] = self.kwargs['categoria_id']
        return context

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = self.object.categoria.slug
        return reverse('menu_categoria_detail', kwargs={'slug': slug})


class ItemDetailView(DetailView):
    model = Item


class ItemUpdateView(UpdateView):
    model = Item
    form_class = ItemForm

menu/templates/menu/categoria_detail.html
{% extends "baseDetail.html" %}
{% load static %}
{% load humanize %}
{% block cTitle %}Detalle de Categoría{% endblock %}
{% block pTitle %}Detalle de Categoría{% endblock %}{% block thhead %}
    <a href="{{ categoria.restaurante.get_absolute_url }}">
        <i class="material-icons"
           style="color: #4285f4 !important">store</i>{{ categoria.restaurante }}</a> &mdash;
    <i class="material-icons" style="color: #9c27b0 !important;">list_view</i>
    {{ categoria.nombre }}{% if request.user.is_superuser %}
        <span class="tools-modal-trigger right">
        <a id="curPos_C{{ categoria.id }}"
           s href="#modal_C{{ categoria.id }}"
           class="modal-trigger"
           onclick="openModal_C{{ categoria.id }}()">
            <i class="material-icons">more_horiz</i></a>
    </span>{% endif %}{% endblock %}
{% block thbody %}
    {#    <tr>#}
    {#        <td class="text-right table-col-label">Categoría</td>#}
    {#        <td class=""><strong>{{ categoria }}</strong></td>#}
    {#    </tr>#}
    <tr>
        <td class="text-right table-col-label">Secuencia</td>
        <td class=""><strong>{{ categoria.orden }}</strong></td>
    </tr>
    <tr>
        <td class="text-right">Activa</td>
        <td class=""><strong>{{ categoria.activa|yesno }}</strong></td>
    </tr>
    <tr>
        <td class="text-right">Altura</td>
        <td class=""><strong>{{ categoria.mask_height }}</strong></td>
    </tr>{% comment %}
    <tr>
        <td class="text-right">Restaurante</td>
        <td class=""><strong>{{ categoria.restaurante }}</strong></td>
    </tr>
    <tr>
        <td class="text-right">Creada</td>
        <td class=""><em>{{ categoria.creada|date:'D d/M/Y' }}</em></td>
    </tr>
    <tr>
        <td class="text-right">Actualizada</td>
        <td class=""><em>{{ categoria.actualizada|date:'D d/M/Y' }}</em></td>
    </tr>{% endcomment %}{% endblock %}
{% block tdhead %}
    <th data-priority="2">Secuencia</th>
    <th data-priority="1">Plato</th>
    <th data-priority="5">Descripción</th>
    <th class="center" data-priority="3">Precio 1</th>
    <th class="center" data-priority="6">Precio 2</th>
    <th class="center" data-priority="4">Activo</th>
{% endblock %}
{% block tdbody %}
    {% for plato in categoria.items.all %}
        <tr>
            <td>{{ plato.orden }}</td>
            <td><a href="{{ plato.get_absolute_url }}">{% if plato.nivel > 1 %}&nbsp;&nbsp;&nbsp;
                                                                               &hellip;{% endif %}{{ plato }}</a>
                {% if request.user.is_superuser %}
                    <span class="tools-modal-trigger">
                        <a id="curPos_P{{ plato.id }}" href="#" onclick="openModal_P{{ plato.id }}()">
                            <i class="material-icons">more_vert</i></a>
                    </span>
                {% endif %}</td>
            <td>{{ plato.descripcion|default_if_none:"" }}</td>
            <td class="center">{{ plato.precio|default_if_none:"&mdash;" }}</td>
            <td class="center">{{ plato.precio_2|default_if_none:"&mdash;" }}</td>
            <td class="center">{{ plato.activo|yesno }}</td>
        </tr>
    {% endfor %}
{% endblock %}{% block footer %}{% if request.user.is_superuser %}{# minipopup Header #}
    <div class="modal-open">
        <div class="tools-modal-wrapper modal-content" id="modal_C{{ categoria.id }}">
            <ul class="ui-listview">
                <li>
                    <a title="Agregar Categoría Nueva"
                       href="{% url 'menu_categoria_create' restaurante_id=categoria.restaurante.pk %}">
                        <i class="material-icons">add</i> Agregar</a></li>
                <li>
                    <a title="Editar Categoría {{ categoria }}"
                       href="{{ categoria.get_update_url }}">
                        <i class="material-icons">edit</i> Editar</a></li>
                <li>
                    <a title="Eliminar Categoría {{ categoria }}"
                       href="{{ categoria.get_delete_url }}">
                        <i class="material-icons">delete</i> Borrar</a></li>
            </ul>
            <div class="ui-popup-arrow-container ui-popup-arrow-t">
                <div class="ui-popup-arrow ui-body-a ui-overlay-shadow"></div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#curPos_C{{ categoria.id }}').click(function () {
                let offset = $(this).offset();
                $('.modal-open').css({
                    'top': (offset.top + 36),
                    'left': (offset.left - 52)
                });
            });
        });

        function openModal_C{{ categoria.id }}() {
            $('#modal_C{{ categoria.id }}').openModal();
        }
    </script>{% endif %}
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large darkblue">
            <i class="large material-icons">add</i>
        </a>
        <ul>
            <li><a class="btn-floating green darken-1"
                   href="{% url 'menu_item_create' categoria_id=categoria.pk %}"><i
                    class="material-icons">local_dining</i></a>
            </li>
            <li><a class="btn-floating red darken-1"
                   href="{% url 'menu_categoria_create' restaurante_id=categoria.restaurante.pk %}"><i
                    class="material-icons">view_list</i></a>
            </li>
            <li><a class="btn-floating blue darken-1"
                   href="{% url 'menu_restaurante_create' %}"><i class="material-icons">store</i></a></li>
        </ul>
    </div>
    {% if request.user.is_superuser %}
        {% for plato in categoria.items.all %}
            <div class="modal-open">
                <div class="tools-modal-wrapper" id="modal_P{{ plato.id }}">
                    <ul class="ui-listview">
                        <li>
                            <a title="Seleccionar Plato {{ plato }}" data-ajax="false"
                               onclick="window.location.reload(false);"
                               href="{{ plato.get_absolute_url }}">
                                <i class="material-icons">arrow_forward</i> Seleccionar</a></li>
                        <li>
                            <a title="Editar Plato {{ plato }}"
                               href="{{ plato.get_update_url }}">
                                <i class="material-icons">edit</i> Editar</a></li>
                        <li>
                            <a title="Eliminar Plato {{ plato }}"
                               href="{{ plato.get_delete_url }}">
                                <i class="material-icons">delete</i> Borrar</a></li>
                    </ul>
                    <div class="ui-popup-arrow-container ui-popup-arrow-t">
                        <div class="ui-popup-arrow ui-body-a ui-overlay-shadow"></div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#curPos_P{{ plato.id }}').click(function () {
                        let offset = $(this).offset();
                        $('.modal-open').css({
                            'top': (offset.top + 36),
                            'left': (offset.left - 52)
                        });
                    });

                });

                function openModal_P{{ plato.id }}() {
                    $('#modal_P{{ plato.id }}').openModal();
                }
            </script>
        {% endfor %}
        <script>
            $(document).keypress(function (e) {
                let checkWebkitandIE = (e.which === 26 ? 1 : 0);
                let checkMoz = (e.which === 122 && e.ctrlKey ? 1 : 0);

                if (checkWebkitandIE || checkMoz) {
                    window.location = "{% url 'menu_item_create' categoria_id=categoria.pk %}";
                }
            });
        </script>
    {% endif %}
{% endblock %}

menu/templates/menu/categoria_form.html
{% extends "baseForm.html" %}
{% load static %}
{% load material_form %}
{% block cTitle %}Datos de Categoría{% endblock %}
{% block pTitle %}Datos de Categoría{% endblock %}
{% block content %}
    <div class="row valign change-form">
        <div class="col s12 m8 offset-m2 l8 offset-l2">
            <div class="card">
                <span class="card-title grey-text text-darken-2">Categoría</span>
                <p>Estos son los campos del registro de <strong>Categorías</strong> que se pueden editar.</p>
                <form method="post" class="viewform">
                    {% csrf_token %}
                    <input type="hidden" id="id_restaurante" name="restaurante" value="{{r_id }}"/>
                    {% form form=form %}{% endform %}
                    <div class="right-align">
                        <button type="submit" name="_submit" class="waves-effect waves-light btn">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

menu/templates/menu/categoria_list.html
{% extends "baseList.html" %}
{% load humanize %}
{% load static %}{% block cTitle %}Categorías{% endblock %}{% block pTitle %}Categorías{% endblock %}
{% block theader %}
    <th data-priority="3">Secuencia</th>
    <th data-priority="4">Restaurante</th>
    <th data-priority="1">Categoría</th>
    <th data-priority="2">Activa</th>
    <th data-priority="5">Altura</th>
{% endblock %}
{% block tbody %}
    {% for categoria in categoria_list %}
        <tr>
            <td>
                <small>{{ categoria.orden }}</small>
            </td>
            <td>
                <i class="material-icons">store</i>{{ categoria.restaurante }}
            </td>
            <td><a href="{{ categoria.get_absolute_url }}">{{ categoria }}</a>
                {% if request.user.is_superuser %}
                    <span class="tools-modal-trigger">
                        <a id="curPos_C{{ categoria.id }}" href="#" onclick="openModal_C{{ categoria.id }}()">
                            <i class="material-icons">more_vert</i></a>
                    </span>
                {% endif %}</td>
            <td class="center">{{ categoria.activa|yesno }}</td>
            <td class="center">{{ categoria.mask_height }}</td>
        </tr>
    {% endfor %}
{% endblock %}
{% block tdfoot %}
    <td><small>Secuencia</small></td>
    <td><small>Restaurante</small></td>
    <td><small>Categoría</small></td>
    <td><small>Activa</small></td>
    <td><small>Altura</small></td>
{% endblock %}
{% block footer %}{% comment %}
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large darkblue">
            <i class="large material-icons">add</i>
        </a>
        <ul>
            <li><a class="btn-floating blue"
                   href="{% url 'menu_categoria_create' %}"><i class="material-icons">insert_chart</i></a></li>
            <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
            <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
            <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
        </ul>
    </div>{% endcomment %}
    {% if request.user.is_superuser %}
        {% for categoria in categoria_list %}
            <div class="modal-open">
                <div class="tools-modal-wrapper" id="modal_C{{ categoria.id }}">
                    <ul class="ui-listview">
                        <li>
                            <a title="Seleccionar Categoría {{ categoria }}" data-ajax="false"
                               onclick="window.location.reload(false);"
                               href="{{ categoria.get_absolute_url }}">
                                <i class="material-icons">arrow_forward</i> Seleccionar</a></li>
                        <li>
                            <a title="Editar Categoría {{ categoria }}"
                               href="{{ categoria.get_update_url }}">
                                <i class="material-icons">edit</i> Editar</a></li>
                        <li>
                            <a title="Eliminar Categoría {{ categoria }}"
                               href="{{ categoria.get_delete_url }}">
                                <i class="material-icons">delete</i> Borrar</a></li>
                    </ul>
                    <div class="ui-popup-arrow-container ui-popup-arrow-t">
                        <div class="ui-popup-arrow ui-body-a ui-overlay-shadow"></div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">

                $(document).ready(function () {
                    $('#curPos_C{{ categoria.id }}').click(setModalPos);

                    function setModalPos() {
                        let offset = $(this).offset();
                        $('.modal-open').css({
                            'top': (offset.top + 36),
                            'left': (offset.left - 52)
                        });
                    }
                });

                function openModal_C{{ categoria.id }}() {
                    $('#modal_C{{ categoria.id }}').openModal();
                }
            </script>
        {% endfor %}
    {% endif %}
{% endblock %}

menu/templates/menu/index.html
{% extends "baseList.html" %}
{% load humanize %}
{% block cTitle %}Inicio{% endblock %}
{% block pTitle %}Inicio{% endblock %}
{% block content %}
    <div class="row valign change-form">
        <div class="col s12 m8 offset-m2 l8 offset-l2">
            <div class="card">
                {% if request.user.is_authenticated %}
                    <p>Hola {{ request.user.username|title }}, ingresaste por última vez
                       hace {{ request.user.last_login|timesince }}</p>
                {% else %}
                    <p>Bienvenido Invitado!</p>
                    <p>Si deseas ingresar como Usuario Autorizado tienes que autenticarte:</p>
                    <p style="text-align: center"><a class="waves-effect waves-light btn center"
                                                     href="{% url 'iniciar' %}">
                        <i class="material-icons left">lock_open</i>ingresar</a></p>
                {% endif %}
                <table id="table-index" class="striped bordered">
                    <thead>
                    <tr>
                        <th colspan="3" class="center">{{ restaurantes.count }} Restaurantes</th>
                    </tr>
                    <tr>
                        <th class="center"><a class="waves-effect" href="{% url 'menu_restaurante_list' %}">
                            <i class="material-icons" style="color: #4285f4">store</i>Restaurantes</a></th>
                        <th class="center"><a class="waves-effect" href="{% url 'menu_categoria_list' %}">
                            <i class="material-icons" style="color: #9c27b0">view_list</i>Categorías</a></th>
                        <th class="center"><a class="waves-effect" href="{% url 'menu_item_list' %}">
                            <i class="material-icons" style="color: #689f38">local_dining</i>Platos</a></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for restaurante in restaurantes %}
                        <tr>
                            <td>
                                <a href="{{ restaurante.get_absolute_url }}">
                                    <strong>{{ restaurante }}</strong>
                                </a>
                            </td>
                            <td class="center">
                                {{ restaurante.categorias.count }}
                            </td>
                            <td class="center">
                                {{ restaurante.platos }}
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

menu/templates/menu/item_form.html
{% extends "baseForm.html" %}
{% load static %}
{% load material_form %}
{% block cTitle %}Datos de Plato{% endblock %}
{% block pTitle %}Datos de Plato{% endblock %}
{% block content %}
    <div class="row valign change-form">
        <div class="col s12 m8 offset-m2 l8 offset-l2">
            <div class="card">
                <span class="card-title grey-text text-darken-2">Plato</span>
                <p>Estos son los campos del registro de <strong>Platos</strong> que se pueden editar.</p>
                <form method="post" class="viewform">
                    {% csrf_token %}
                    <input type="hidden" id="id_categoria" name="categoria" value="{{ c_id }}"/>
                    {% form form=form %}{% endform %}
                    <div class="right-align">
                        <button type="submit" name="_submit" class="waves-effect waves-light btn">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

menu/templates/menu/restaurante_form.html
{% extends "baseForm.html" %}
{% load static %}
{% load material_form %}
{% block cTitle %}Datos de Restaurante{% endblock %}
{% block pTitle %}Datos de Restaurante{% endblock %}
{% block content %}
{#    <p><a class="btn btn-default" href="{% url 'menu_restaurante_list' %}">Restaurante Listing</a></p>#}
    <div class="row valign change-form">
        <div class="col s12 m8 offset-m2 l8 offset-l2">
            <div class="card">
                <span class="card-title grey-text text-darken-2">Restaurante</span>
                <p>Estos son los campos del registro de <strong>Restaurantes</strong> que se pueden editar.</p>
                <form method="post" class="viewform">
                    {% csrf_token %}
                    {% form form=form %}{% endform %}
                    <div class="right-align">
                        <button type="submit" name="_submit" class="waves-effect waves-light btn">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}